export const MODULE_REGISTRY = {
  home: {
    key: 'home',
    section: '工作台',
    label: '首页',
    description: '查看首页入口与常用业务页面',
    path: '/',
    sidebarKey: 'home',
  },
  'home-personal-dashboard': {
    key: 'home-personal-dashboard',
    section: '工作台',
    label: '我的工作台',
    description: '查看数据简报、今日待办、客户概况和个人业绩进度',
    path: '/dashboard/personal',
    sidebarKey: 'home-personal-dashboard',
  },
  'home-team-dashboard': {
    key: 'home-team-dashboard',
    section: '工作台',
    label: '团队作战图',
    description: '查看团队目标进度、预警信息和督促日志',
    path: '/dashboard/team',
    sidebarKey: 'home-team-dashboard',
  },
  'home-performance': {
    key: 'home-performance',
    section: '工作台',
    label: '业绩目标',
    description: '维护公司月度系统成交目标与新增客户目标',
    path: '/home/performance-target',
    sidebarKey: 'home-performance',
  },
  'home-order-binding': {
    key: 'home-order-binding',
    section: '工作台',
    label: '订单关联',
    description: '配置 OA 客户与企业订单分成归属关系',
    path: '/home/order-binding',
    sidebarKey: 'home-order-binding',
  },
  'home-divided-config': {
    key: 'home-divided-config',
    section: '工作台',
    label: '分成配置',
    description: '统一维护系统服务费与供应链分成标准化规则',
    path: '/home/divided-config',
    sidebarKey: 'home-divided-config',
  },
  customer: {
    key: 'customer',
    section: '客户管理',
    label: '客户管理',
    description: '查看客户列表、跟进状态和公海归属',
    path: '/customer',
    sidebarKey: 'customer',
  },
  channel: {
    key: 'channel',
    section: '渠道管理',
    label: '渠道管理',
    description: '维护渠道列表、负责人和合同归档信息',
    path: '/channel',
    sidebarKey: 'channel',
  },
  leads: {
    key: 'leads',
    section: '销售线索',
    label: '线索管理',
    description: '筛选、分配、清洗并维护销售线索',
    path: '/sales/leads',
    sidebarKey: 'leads',
  },
  'ai-assign': {
    key: 'ai-assign',
    section: '销售线索',
    label: 'AI智能分配',
    description: '审阅 AI 预分配结果并回写业务闭环',
    path: '/sales/leads/ai-assign',
    sidebarKey: 'leads',
  },
  pitch: {
    key: 'pitch',
    section: '销售线索',
    label: 'AI推客',
    description: '按线索节奏跟进并实时回写处理结果',
    path: '/sales/pitch',
    sidebarKey: 'pitch',
  },
  'people-all': {
    key: 'people-all',
    section: '员工管理',
    label: '全部员工',
    description: '查看员工账号、直属关系和业务负载',
    path: '/people/all',
    sidebarKey: 'people-all',
  },
  'people-direct': {
    key: 'people-direct',
    section: '员工管理',
    label: '直属员工',
    description: '查看直属员工账号、客户与渠道负责情况',
    path: '/people/direct',
    sidebarKey: 'people-direct',
  },
  profile: {
    key: 'profile',
    section: '员工管理',
    label: '销售画像',
    description: '基于实时线索与跟进结果刷新团队画像',
    path: '/people/profile',
    sidebarKey: 'profile',
  },
  'finance-supplier': {
    key: 'finance-supplier',
    section: '财务管理',
    label: '供应商对账款',
    description: '处理账款筛选、对账明细与凭证信息',
    path: '/finance/supplier',
    sidebarKey: 'finance-supplier',
  },
  'finance-system-fee': {
    key: 'finance-system-fee',
    section: '财务管理',
    label: '系统服务费',
    description: '查看系统服务费订单、凭证和开票状态',
    path: '/finance/system-fee',
    sidebarKey: 'finance-system-fee',
  },
  'finance-staff-bill': {
    key: 'finance-staff-bill',
    section: '财务管理',
    label: '员工对账单',
    description: '查看员工结算、核算状态和打款进度',
    path: '/finance/staff-bill',
    sidebarKey: 'finance-staff-bill',
  },
  'finance-staff-correct': {
    key: 'finance-staff-correct',
    section: '财务管理',
    label: '员工账单校正',
    description: '处理员工账单校正申请与利润差异',
    path: '/finance/staff-correct',
    sidebarKey: 'finance-staff-correct',
  },
  'finance-channel-bill': {
    key: 'finance-channel-bill',
    section: '财务管理',
    label: '渠道对账单',
    description: '查看渠道分成结算、核算和打款进度',
    path: '/finance/channel-bill',
    sidebarKey: 'finance-channel-bill',
  },
  'finance-channel-correct': {
    key: 'finance-channel-correct',
    section: '财务管理',
    label: '渠道账单校正',
    description: '查看渠道账单校正申请与提成调整',
    path: '/finance/channel-correct',
    sidebarKey: 'finance-channel-correct',
  },
  'finance-customer-correct': {
    key: 'finance-customer-correct',
    section: '财务管理',
    label: '客户账单校正',
    description: '查看客户订单校正与靠铺分成信息',
    path: '/finance/customer-correct',
    sidebarKey: 'finance-customer-correct',
  },
  'finance-settle-list': {
    key: 'finance-settle-list',
    section: '财务管理',
    label: '结算订单列表',
    description: '查看订单支付、结算和归档状态',
    path: '/finance/settle-list',
    sidebarKey: 'finance-settle-list',
  },
  'finance-commission': {
    key: 'finance-commission',
    section: '财务管理',
    label: '提成管理',
    description: '查看提成规则配置、月度汇总和发放状态',
    path: '/finance/commission',
    sidebarKey: 'finance-commission',
  },
  'reports-daily': {
    key: 'reports-daily',
    section: '工作报告',
    label: 'AI日报/周报',
    description: '录入日报、查看历史记录和 AI 周报汇总',
    path: '/reports/daily',
    sidebarKey: 'reports-daily',
  },
  'settings-reminders': {
    key: 'settings-reminders',
    section: '系统设置',
    label: '督促规则配置',
    description: '维护督促规则、特殊预警和消息模板',
    path: '/settings/reminders',
    sidebarKey: 'settings-reminders',
  },
  personal: {
    key: 'personal',
    section: '个人中心',
    label: '个人中心',
    description: '维护账号安全、消息列表和收款信息',
    path: '/personal',
    sidebarKey: 'personal',
  },
};

const MATCH_ORDER = [
  'ai-assign',
  'home-personal-dashboard',
  'home-team-dashboard',
  'home-performance',
  'home-order-binding',
  'home-divided-config',
  'reports-daily',
  'settings-reminders',
  'finance-commission',
  'finance-system-fee',
  'finance-staff-bill',
  'finance-staff-correct',
  'finance-channel-bill',
  'finance-channel-correct',
  'finance-customer-correct',
  'finance-settle-list',
  'finance-supplier',
  'people-all',
  'people-direct',
  'profile',
  'pitch',
  'leads',
  'customer',
  'channel',
  'personal',
  'home',
];

export function getPathForModule(moduleKey) {
  return MODULE_REGISTRY[moduleKey]?.path || '/';
}

export function getCurrentModule(pathname) {
  const matchedKey = MATCH_ORDER.find((key) => {
    const module = MODULE_REGISTRY[key];
    if (!module) return false;
    if (module.path === '/') return pathname === '/';
    return pathname.startsWith(module.path);
  });

  return MODULE_REGISTRY[matchedKey || 'home'];
}

export function getSidebarModuleKey(pathname) {
  return getCurrentModule(pathname).sidebarKey || 'home';
}